QuanLyNongSan/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views  # Replace 'app' with the actual name of your app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('shop/', views.shop, name="shop"),
    path('shop-detail/<str:idnongsan>/', views.shop_detail, name='shop-detail'),
    path('contact/', views.contact, name="contact"),
    path('cart/', views.cart, name="cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('login/', views.login, name="login"),
    path('register/', views.register, name="register"),
    path('manage/', views.manage, name="manage"),
    path('nongsan/', views.nongsan, name="nongsan"),
    path('nongsan/<str:IdNongSan>/', views.nongsan, name='nongsan_detail'),
    path('logout/', views.logout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('giamgia/', views.giamgia, name="giamgia"),
    path('giamgia/<str:magiamgia>/', views.giamgia, name='giamgia_detail'),
    path('nhanvien/', views.nhanvien, name="nhanvien"),
    path('order/', views.order, name="order"),
    path('order/<str:madonhang>/', views.order, name='order_detail'),
    path('donhangdetail/', views.donhangdetail, name="donhangdetail"),
    path('donhangdetail/<str:ma_donhang_detail>/', views.donhangdetail, name='donhangdetail_detail'),
    path('add_to_cart/<str:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('order-history/', views.order_history, name='order_history'),
    path('kho/', views.kho, name="kho"),
    path('kho/<str:idkho>/', views.kho, name="kho_hh"),
    path('tonkho/', views.tonkho, name="tonkho"),
    path('tonkho/<str:idtonkho>/', views.tonkho, name="tonkho_hh"),
    path('nhacungcap/', views.nhacungcap, name="nhacungcap"),
    path('nhacungcap/<str:manhacungcap>/', views.nhacungcap, name="nhacungcap_hh"),
    path('ordernhacungcap/', views.ordernhacungcap, name="ordernhacungcap"),
    path('ordernhacungcap/<str:idorder>/', views.ordernhacungcap, name="ordernhacungcap_hh"),
    path('nhanvien/<str:manhanvien>/', views.nhanvien, name='nhanvien_detail'),
    path('account/', views.account, name="account"),
    path('account/<str:idtaikhoan>/', views.account, name="account_detail"),
    path('nguoidung/', views.nguoidung, name="nguoidung"),
    path('nguoidung/<str:manguoidung>/', views.nguoidung, name='nguoidung_detail'),
    path('profile-manage/', views.profileManage, name="profile-manage"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('cart/delete/<str:item_id>/', views.delete_cart_item, name='delete_cart_item'),
    path('cart/update/<str:item_id>/', views.update_cart_item, name='update_cart_item'),
    path('shop-detail/<str:product_id>/', views.shop_detail, name='shop-detail'),
    path('danhmuc/', views.danhmuc, name="danhmuc"),
    path('danhmuc/<str:id_danhmuc>/', views.danhmuc, name="danhmuc-detail"),
    path('order_received/<str:order_id>/', views.order_received, name='order_received'),
    path('cancel_order/<str:madonhang>/', views.cancel_order, name='cancel_order'),
    path('doanh-thu-ngay/', views.doanh_thu_theo_ngay, name='doanh_thu_ngay'),
]

app/models.py
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Danhmuc(models.Model):
    madanhmuc = models.CharField(db_column='MaDanhMuc', primary_key=True, max_length=50)  # Field name made lowercase.
    tendanhmuc = models.CharField(db_column='TenDanhMuc', max_length=100, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'danhmuc'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Donhang(models.Model):
    madonhang = models.CharField(db_column='MaDonHang', primary_key=True, max_length=50)  # Field name made lowercase.
    manguoidung = models.ForeignKey('Nguoidung', models.DO_NOTHING, db_column='MaNguoiDung', blank=True, null=True)  # Field name made lowercase.
    tonggia = models.DecimalField(db_column='TongGia', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    ngaydat = models.DateTimeField(db_column='NgayDat', blank=True, null=True)  # Field name made lowercase.
    trangthai = models.CharField(db_column='TrangThai', max_length=50, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'donhang'


class Giamgia(models.Model):
    magiamgia = models.CharField(db_column='MaGiamGia', primary_key=True, max_length=50)  # Field name made lowercase.
    idnongsan = models.ForeignKey('Nongsan', models.DO_NOTHING, db_column='IdNongSan', blank=True, null=True)  # Field name made lowercase.
    phantramgiam = models.DecimalField(db_column='PhanTramGiam', max_digits=5, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    ngaybatdau = models.DateField(db_column='NgayBatDau', blank=True, null=True)  # Field name made lowercase.
    ngayketthuc = models.DateField(db_column='NgayKetThuc', blank=True, null=True)  # Field name made lowercase.
    mota = models.TextField(db_column='MoTa', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'giamgia'


class Kho(models.Model):
    idkho = models.CharField(db_column='IdKho', primary_key=True, max_length=50)  # Field name made lowercase.
    name = models.CharField(db_column='Name', max_length=100, blank=True, null=True)  # Field name made lowercase.
    diachi = models.CharField(db_column='DiaChi', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'kho'


class Nguoidung(models.Model):
    manguoidung = models.CharField(db_column='MaNguoiDung', primary_key=True, max_length=50)  # Field name made lowercase.
    hovaten = models.CharField(db_column='HoVaTen', max_length=100, blank=True, null=True)  # Field name made lowercase.
    diachi = models.CharField(db_column='DiaChi', max_length=255, blank=True, null=True)  # Field name made lowercase.
    phone = models.CharField(db_column='Phone', max_length=20, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=100, blank=True, null=True)  # Field name made lowercase.
    idtaikhoan = models.ForeignKey('Taikhoan', models.DO_NOTHING, db_column='IdTaiKhoan', blank=True, null=True)  # Field name made lowercase.
    image=models.ImageField(upload_to='nguoidung',null=True, blank=True)
    class Meta:
        managed = False
        db_table = 'nguoidung'
  
class Nhacungcap(models.Model):
    manhacungcap = models.CharField(db_column='MaNhaCungCap', primary_key=True, max_length=50)  # Field name made lowercase.
    tennhacungcap = models.CharField(db_column='TenNhaCungCap', max_length=100, blank=True, null=True)  # Field name made lowercase.
    diachi = models.CharField(db_column='DiaChi', max_length=255, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=100, blank=True, null=True)  # Field name made lowercase.
    sdt = models.CharField(db_column='SDT', max_length=20, blank=True, null=True)  # Field name made lowercase.
    nongsanid = models.ForeignKey('Nongsan', models.DO_NOTHING, db_column='NongSanId', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'nhacungcap'


class Nhanvien(models.Model):
    manhanvien = models.CharField(db_column='MaNhanVien', primary_key=True, max_length=50)  # Field name made lowercase.
    tennhanvien = models.CharField(db_column='TenNhanVien', max_length=100, blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='Email', max_length=100, blank=True, null=True)  # Field name made lowercase.
    sodienthoai = models.CharField(db_column='SoDienThoai', max_length=20, blank=True, null=True)  # Field name made lowercase.
    luong = models.DecimalField(db_column='Luong', max_digits=12, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    calamviec = models.CharField(db_column='CaLamViec', max_length=50, blank=True, null=True)  # Field name made lowercase.
    idtaikhoan = models.ForeignKey('Taikhoan', models.DO_NOTHING, db_column='IdTaiKhoan', blank=True, null=True)  # Field name made lowercase.
    image=models.ImageField(upload_to='nhanvien/',null=True, blank=True)
    class Meta:
        managed = False
        db_table = 'nhanvien'


class Nongsan(models.Model):
    idnongsan = models.CharField(db_column='IdNongSan', primary_key=True, max_length=50)  # Field name made lowercase.
    ten = models.CharField(db_column='Ten', max_length=100, blank=True, null=True)  # Field name made lowercase.
    mota = models.TextField(db_column='MoTa', blank=True, null=True)  # Field name made lowercase.
    gia = models.DecimalField(db_column='Gia', max_digits=15, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    trongluong = models.DecimalField(db_column='TrongLuong', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.
    madanhmuc = models.ForeignKey(Danhmuc, models.DO_NOTHING, db_column='MaDanhMuc', blank=True, null=True)  # Field name made lowercase.
    image=models.ImageField(upload_to='nongsan/',null=True, blank=True )
    class Meta:
        managed = False
        db_table = 'nongsan'

class DonHangDetail(models.Model):
        ma_donhang_detail = models.CharField(max_length=255, primary_key=True,db_column='MaDonHangDetail')
        ma_donhang = models.ForeignKey(Donhang, on_delete=models.CASCADE, db_column='MaDonHang')
        id_nongsan = models.ForeignKey(Nongsan, on_delete=models.CASCADE, db_column='IdNongSan')

app/templates/user/cart.html
{% include "user/header.html" %} {% load static %}

<!-- Modal Search Start -->
<div
  class="modal fade"
  id="searchModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content rounded-0">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body d-flex align-items-center">
        <div class="input-group w-75 mx-auto d-flex">
          <input
            type="search"
            class="form-control p-3"
            placeholder="keywords"
            aria-describedby="search-icon-1"
          />
          <span id="search-icon-1" class="input-group-text p-3"
            ><i class="fa fa-search"></i
          ></span>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal Search End -->

<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
  <h1 class="text-center text-white display-6">Cart</h1>
  <ol class="breadcrumb justify-content-center mb-0">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="#">Pages</a></li>
    <li class="breadcrumb-item active text-white">Cart</li>
  </ol>
</div>
<!-- Single Page Header End -->

<!-- Cart Page Start -->
<div class="container-fluid py-5">
  {% if messages %}
    <div class="ml-4">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-slide" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
  <div class="container py-5">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Products</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          {% if cart_items %}
            {% for item in cart_items %}
              <tr>
                <th scope="row">
                  <div class="d-flex align-items-center">
                    <img
                      src="{{ item.nongsan.image.url }}"
                      class="img-fluid me-5 rounded-circle"
                      style="width: 80px; height: 80px"
                      alt="{{ item.nongsan.ten }}"
                    />
                  </div>
                </th>
                <td>
                  <p class="mb-0 mt-4">{{ item.nongsan.ten }}</p> <!-- Hiển thị tên sản phẩm -->
                </td>
                <td>
                  {% if item.price < item.nongsan.gia %}
                    <p class="mb-0 mt-4">
                      <del>{{ item.nongsan.gia|floatformat:0 }} VNĐ</del>
                      <br>
                      {{ item.price|floatformat:0 }} VNĐ
                    </p> <!-- Hiển thị giá đã giảm -->
                  {% else %}
                    <p class="mb-0 mt-4">{{ item.nongsan.gia|floatformat:0 }} VNĐ</p> <!-- Hiển thị giá gốc -->
                  {% endif %}
                </td>
                <td>
                  <form action="{% url 'update_cart_item' item.cart_id %}" method="post" class="input-group quantity mt-4" style="width: 100px">
                    {% csrf_token %}
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-sm btn-minus rounded-circle bg-light border" onclick="this.parentElement.nextElementSibling.stepDown(); this.parentElement.nextElementSibling.onchange();">
                            <i class="fa fa-minus"></i>
                        </button>
                    </div>
                    <input
                        type="number"
                        class="form-control form-control-sm text-center border-0"
                        name="quantity"
                        value="{{ item.quantity }}"
                        min="1"
                        onchange="this.form.submit();"
                    >
                    <div class="input-group-btn">
                        <button type="button" class="btn btn-sm btn-plus rounded-circle bg-light border" onclick="this.parentElement.previousElementSibling.stepUp(); this.parentElement.previousElementSibling.onchange();">
                            <i class="fa fa-plus"></i>
                        </button>
                    </div>
                </form>
                </td>
                <td>
                  <p class="mb-0 mt-4">{{ item.total_price|floatformat:0 }} VNĐ</p> <!-- Tính toán tổng giá -->
                </td>
                <td>
                 
                  <a href="{% url 'delete_cart_item' item.cart_id %}" class="btn btn-md btn-danger rounded-circle bg-light border ml-2 mt-3">
                    <i class="fa fa-times text-danger"></i>
                </a>
                </td>
              </tr>
            {% endfor %}
          {% else %}
            <tr>
              <td colspan="6" class="text-center">Giỏ hàng của bạn đang trống</td>
            </tr>
          {% endif %}
        </tbody>
      </table>
    </div>
    <div class="mt-5">
     
      <a href="/shop/"
        class="btn border-secondary rounded-pill px-4 py-3 text-primary"
        type="button"
      >
        Tiếp tục mua hàng
      </a>
    </div>
    <div class="row g-4 justify-content-end">
      <div class="col-8"></div>
      <div class="col-sm-8 col-md-7 col-lg-6 col-xl-4">
        <div class="bg-light rounded">
          <div class="p-4">
            <h1 class="display-6 mb-4">
              Cart <span class="fw-normal">Total</span>
            </h1>
           
            
          </div>
          <div
            class="py-4 mb-4 border-top border-bottom d-flex justify-content-between"
          >
            <h5 class="mb-0 ps-4 me-4">Total</h5>
            <p class="mb-0 pe-4">{{total_price |floatformat:0 }} VNĐ </p>
          </div>
          <a
            class="btn border-secondary rounded-pill px-4 py-3 text-primary text-uppercase mb-4 ms-4"
            href="{%url "checkout"%}"
          >
            Proceed Checkout
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Cart Page End -->

{% include "user/footer.html"%}

app/templates/user/contact.html
{% include "user/header.html" %} {% load static %}

<!-- Modal Search Start -->
<div
  class="modal fade"
  id="searchModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content rounded-0">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body d-flex align-items-center">
        <div class="input-group w-75 mx-auto d-flex">
          <input
            type="search"
            class="form-control p-3"
            placeholder="keywords"
            aria-describedby="search-icon-1"
          />
          <span id="search-icon-1" class="input-group-text p-3"
            ><i class="fa fa-search"></i
          ></span>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal Search End -->

<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
  <h1 class="text-center text-white display-6">Contact</h1>
  <ol class="breadcrumb justify-content-center mb-0">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active text-white">Contact</li>
  </ol>
</div>
<!-- Single Page Header End -->

<!-- Contact Start -->
<div class="container-fluid contact py-5">
  <div class="container py-5">
    <div class="p-5 bg-light rounded">
      <div class="row g-4">
        <div class="col-12">
          <div class="text-center mx-auto" style="max-width: 700px">
            <h1 class="text-primary">Liên hệ chúng tôi</h1>
            
          </div>
        </div>
        <div class="col-lg-12">
          <div class="h-100 rounded">
           
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7447.573600609299!2d105.742166!3d21.041215!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135096b31fa7abb%3A0xff645782804911af!2zVHLGsOG7nW5nIMSR4bqhaSBo4buNYyBDw7RuZyBuZ2jhu4cgxJDDtG5nIMOB!5e0!3m2!1svi!2sus!4v1720146783417!5m2!1svi!2sus" 
            class="rounded w-100"
            
            width="600" 
            height="450" 
            style="border:0;" 
            allowfullscreen="" 
            loading="lazy" 
            referrerpolicy="no-referrer-when-downgrade"></iframe>
          </div>
        </div>
      
        <div class="row">
          <div class="d-flex p-4 rounded mb-4 bg-white ">
            <i class="fas fa-map-marker-alt fa-2x text-primary me-4 "></i>
            <div>
              <h4>Address</h4>
              <p class="mb-2">Đại học công nghệ Đông  Á</p>
            </div>
          </div>
          <div class="d-flex p-4 rounded mb-4 bg-white">
            <i class="fas fa-envelope fa-2x text-primary me-4"></i>
            <div>
              <h4>Mail Us</h4>
              <p class="mb-2">20212043@eaut.edu.vn</p>
            </div>
          </div>
          <div class="d-flex p-4 rounded bg-white">
            <i class="fa fa-phone-alt fa-2x text-primary me-4"></i>
            <div>
              <h4>Telephone</h4>
              <p class="mb-2">(+84) 363 273 201</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Contact End -->

{% include "user/footer.html"%}

app/templates/user/orderHistory.html
{% include "user/header.html" %} {% load static %}
{% load humanize %}
<style type="text/css">

  body {
    font-family: 'Arial', sans-serif;
  }
  
  .container-fluid {
    background-color: #f8f9fa;
  }
  
  .card {
    border: none;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
  }
  
  .card-header {
    background-color: #679d06;
    color: #ffffff;
    border-bottom: none;
    font-weight: bold;
  }
  
  .card-body {
    background-color: #ffffff;
  }
  
  .list-group-item {
    border: none;
    padding: 10px 20px;
    background-color: #f8f9fa;
  }
  
  .img-thumbnail {
    border: none;
  }
  
  .btn-success {
    background-color: #28a745;
    border: none;
  }
  
  .btn-danger {
    background-color: #dc3545;
    border: none;
  }
  
  .btn-primary {
    background-color: #007bff;
    border: none;
  }
  
  .badge-light {
    background-color: #ffffff;
    color: #007bff;
  }
  
  .alert {
    margin-top: 20px;
  }
   
</style>
<!-- Modal Search Start -->
<div
  class="modal fade"
  id="searchModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-fullscreen">
    <div class="modal-content rounded-0">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Search by keyword</h5>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <div class="modal-body d-flex align-items-center">
        <div class="input-group w-75 mx-auto d-flex">
          <input
            type="search"
            class="form-control p-3"
            placeholder="keywords"
            aria-describedby="search-icon-1"
          />
          <span id="search-icon-1" class="input-group-text p-3"
            ><i class="fa fa-search"></i
          ></span>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Modal Search End -->

<!-- Single Page Header start -->
<div class="container-fluid page-header py-5">
  <h1 class="text-center text-white display-6">Cart History</h1>
  <ol class="breadcrumb justify-content-center mb-0">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active text-white">History order</li>
  </ol>
</div>
<!-- Single Page Header End -->

<!-- Cart Page Start -->
<div class="container-fluid py-5">
  <div class="container py-5">
    {% if orders %}
      {% for order in orders %}
        <div class="card mb-3">
          <div class="card-header d-flex justify-content-between align-items-center">
            <div>
              <strong>Mã đơn hàng:</strong> {{ order.madonhang }}<br>
              <small>Ngày mua: {{ order.ngaydat }}</small>
            </div>
            <div class="badge badge-secondary">{{ order.trangthai }}</div>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-md-8">
                <ul class="list-group list-group-flush">
                  {% for detail in order.donhangdetail_set.all %}
                    <li class="list-group-item">
                      <div class="d-flex align-items-center">
                        {% if detail.id_nongsan.image %}
                          <img src="{{ detail.id_nongsan.image.url }}" alt="{{ detail.id_nongsan.ten }}" class="img-thumbnail mr-3" width="100">
                        {% endif %}
                        <div>
                          <strong>Sản phẩm:</strong> {{ detail.id_nongsan.ten }}<br>
                          <strong>Số lượng:</strong> {{ detail.quantity }}<br>
                          <strong>Giá:</strong> {{ detail.id_nongsan.gia | intcomma }} đ
                        </div>
                      </div>
                    </li>
                  {% endfor %}
                </ul>
              </div>
              <div class="col-md-4 text-right">
                <div class="mb-3">
                  <strong>Thành tiền:</strong> {{ order.tonggia | intcomma }} đ
                </div>
                {% if order.trangthai == "Completed" %}
                <a href="{% url 'order_received' order.madonhang %}" class="btn btn-primary mb-2">Đã nhận hàng</a>
              {% endif %}
              {% if order.trangthai != "Đã nhận hàng" and order.trangthai != "Bị Huỷ" and order.trangthai != "Completed" %}
                <a href="{% url 'cancel_order' order.madonhang %}" class="btn btn-danger mb-2">Hủy đơn</a>
              {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div class="alert alert-info text-center" role="alert">
        Không có đơn hàng nào.
      </div>
    {% endif %}
  </div>
</div>


<!-- Cart Page End -->

{% include "user/footer.html" %}

app/templates/user/password_reset_complete.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Password reset complete</h2>
  <p>Your password has been set. You may go ahead and log in now.</p>
  <a href="{% url 'login' %}">Log in</a>
{% endblock %}